### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kevin-nicolli** [RyanNielson/laravel-facades#2] opened 2015-02-05 05:08 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
<unknown> (/home/nico/.atom/packages/laravel-facades/lib/laravel-facades.coffee:43:13)
```

**Comment by RyanNielson** [comment] 2015-02-05 14:38
I haven't used Atom recently, but I'll try to find some time and look into this. Thanks for the report, although it is a duplicate of #1.

**Closed by RyanNielson** 2015-02-05 14:38 UTC
